/** Generated by bkr export. Do not edit by hand. */
/** Brand: ridgeline-coffee. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "ink": "#2B1A12",
      "body": "#4A3A30",
      "surface": "#FAF4EA",
      "white": "#FFFFFF",
      "copper": "#B4501E",
      "on-primary": "#FFFFFF",
      "link": "#9A3F14",
      "sage": "#8FA68A",
      "card": "#F1E6D6"
    }
  },
  "fontFamily": {
    "heading": [
      "DM Serif Display",
      "Georgia",
      "Times New Roman",
      "serif"
    ],
    "body": [
      "DM Sans",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "sans-serif"
    ]
  },
  "fontWeight": {
    "regular": "400",
    "bold": "700"
  },
  "fontSize": {
    "small": "0.875rem",
    "base": "1rem",
    "large": "1.25rem",
    "heading": "2rem",
    "display": "3rem"
  },
  "lineHeight": {
    "tight": "1.15",
    "normal": "1.6"
  }
};
