/** Generated by bkr export. Do not edit by hand. */
/** Brand: cedar-hollow-pantry. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2F6B3A",
      "on-primary": "#FFFFFF",
      "link": "#2F6B3A",
      "ink": "#1F2A24",
      "body": "#3D4A42",
      "surface": "#FFFDF8",
      "harvest": "#E8902E"
    }
  },
  "fontFamily": {
    "heading": [
      "Atkinson Hyperlegible",
      "Verdana",
      "sans-serif"
    ],
    "body": [
      "Atkinson Hyperlegible",
      "Verdana",
      "sans-serif"
    ]
  },
  "fontWeight": {
    "regular": "400",
    "bold": "700"
  },
  "fontSize": {
    "base": "1.125rem",
    "large": "1.5rem",
    "heading": "2.25rem"
  }
};
