import fs from "node:fs";
import path from "node:path";
import { ensureDir, pathExists, readManifest, writeText } from "./fs-kit.js";
import { resolveVisibility } from "./publication.js";

const DEFAULT_MAX_BYTES = 12000;

function readHead(filePath, maxChars = 2000) {
  if (!pathExists(filePath)) return "";
  const raw = fs
    .readFileSync(filePath, "utf8")
    .replace(/<!--[\s\S]*?-->\n?/g, "")
    .trim();
  return raw.length > maxChars ? `${raw.slice(0, maxChars)}\n…` : raw;
}

function bulletLinesFromMarkdown(md, maxItems = 10) {
  return md
    .split("\n")
    .filter((line) => /^[-*]/.test(line.trim()))
    .slice(0, maxItems)
    .join("\n");
}

const SHARING_RULE = {
  private: "Private: do not send files from this kit outside the organization.",
  partner: "Partner: only paths in `publication.includedPaths` may go to partners. Build them with `bkr publish`.",
  public: "Public: only paths in `publication.includedPaths` may be shared publicly. Build them with `bkr publish`.",
};

export function buildDigest(kitRoot, options = {}) {
  const maxBytes = options.maxBytes || DEFAULT_MAX_BYTES;
  const manifest = readManifest(kitRoot);
  const visibility = resolveVisibility(manifest);
  const read = (rel, n) => readHead(path.join(kitRoot, rel), n);

  const about = read("identity/about.md", 1500);
  const tone = read("voice/tone.md", 1500);
  const messaging = read("copy/messaging.md", 1200);
  const logo = read("visual/logo.md", 1200);
  const vocabulary = bulletLinesFromMarkdown(read("voice/vocabulary.md", 2500));
  const hasBrief = pathExists(path.join(kitRoot, "tokens", "exports", "agent", "ui-brief.md"));

  let body = `# Agent context (generated)

> Regenerate with \`bkr digest\`. Normative values live in \`tokens/*.bkr.json\` and \`tokens/exports/\`.

## Brand

- **Id:** ${manifest.brand.id}
- **Name:** ${manifest.brand.displayName}
- **Status:** ${manifest.brand.status}
- **Role:** ${manifest.role}
- **Sharing:** ${SHARING_RULE[visibility]}
`;

  if (manifest.hierarchy?.parent) {
    body += `- **Parent kit:** ${manifest.hierarchy.parent.repository} @ ${manifest.hierarchy.parent.ref}\n`;
  }
  if (manifest.contacts?.security) {
    body += `- **Report impersonation to:** ${manifest.contacts.security}\n`;
  }

  const sections = [
    ["Identity (excerpt)", about],
    ["Voice (excerpt)", tone],
    ["Vocabulary highlights", vocabulary],
    ["Approved messaging (excerpt)", messaging],
    ["Logo rules (excerpt)", logo],
  ].filter(([, text]) => text);
  for (const [title, text] of sections) {
    body += `
## ${title}

${text}
`;
  }

  body += `
## Consumption

- CSS variables: \`${manifest.consumption.cssVariables}\`
${hasBrief ? "- UI brief (colors, type, approved contrast pairs): `tokens/exports/agent/ui-brief.md`\n" : ""}- Do not invent hex values or fonts outside exported tokens.
- Load full \`copy/legal.md\` before external publication.
`;

  if (Buffer.byteLength(body, "utf8") > maxBytes) {
    body = `${body.slice(0, maxBytes - 20)}\n\n… [truncated]\n`;
  }

  const digestPath = path.join(kitRoot, manifest.consumption.agentDigest);
  ensureDir(path.dirname(digestPath));
  writeText(digestPath, body);

  const agentsPath = path.join(kitRoot, "AGENTS.md");
  const agentsDoc = `# Agent instructions (BKR)

This repository follows the **Brand Kit Repository (BKR)** layout (\`ght.brandkit/v1\`, spec ${manifest.specVersion}).
Generated by \`bkr digest\`. Do not edit by hand.

## Load order

1. \`brandkit.yaml\`: profiles, role, parent kit, sharing rules
2. \`${manifest.consumption.agentDigest}\`: size-capped summary (generated)
3. For UI work: \`tokens/exports/agent/ui-brief.md\` and \`tokens/exports/css/variables.css\`
4. As needed: \`voice/\`, \`visual/logo.md\`, \`copy/\`

## Rules

- **Tokens win** over prose for hex, spacing, and type scales.
- **Product kits** inherit palette rules from \`hierarchy.parent\`; do not introduce a second primary.
- Only pair text and background colors listed in \`validation.contrastPairs\` unless you check contrast.
- **Sharing:** ${SHARING_RULE[visibility]}
- Never copy staff names, emails, or phone numbers into shared or public material.
- After editing tokens or the manifest, run \`bkr export --all\`, then \`bkr digest\`, then \`bkr validate\`.

## Human docs

See \`README.md\` for the file index and \`tokens/exports/html/brand-at-a-glance.html\` for a visual summary.
`;

  writeText(agentsPath, agentsDoc);

  return { digestPath, agentsPath, bytes: Buffer.byteLength(body, "utf8") };
}
