import fs from "node:fs";
import path from "node:path";
import {
  TOKEN_SCHEMA_URL,
  listFiles,
  pathExists,
  readJson,
  readManifest,
  sha256,
  writeJson,
  writeText,
} from "./fs-kit.js";
import {
  cssPrefix,
  cssVarName,
  kebab,
  loadTokens,
  toCssValue,
  toDtcgValue,
  toPosix,
} from "./tokens.js";
import { buildBrandAtAGlance, buildUiBrief, logoDataUri } from "./brief.js";

// Bump when export output changes shape so existing kits are flagged as stale.
const EXPORT_FORMAT = "bkr-export-3";
export const ALL_TARGETS = ["dtcg", "css", "tailwind", "html", "agent"];
export const HASH_FILE = path.join("tokens", "exports", ".bkr-export-hash");

const GENERATED = "Generated by bkr export. Do not edit by hand.";

// --- Source hash ---------------------------------------------------------------
// Covers everything exports are built from: manifest, token files, and logo files.
// Uses parsed JSON/YAML so Windows line endings do not change the hash.
export function computeSourceHash(kitRoot) {
  const manifest = readManifest(kitRoot);
  const tokens = loadTokens(kitRoot);
  const parts = [EXPORT_FORMAT, JSON.stringify(manifest)];
  for (const f of tokens.files) {
    parts.push(`${f.rel}=${JSON.stringify(f.doc)}`);
  }
  for (const f of listFiles(path.join(kitRoot, "assets", "logo"))) {
    const rel = toPosix(path.relative(kitRoot, f));
    const embeddable = /\.(svg|png|jpe?g|webp|ico)$/i.test(rel);
    parts.push(`${rel}=${embeddable ? sha256(logoDataUri(kitRoot, rel)) : ""}`);
  }
  return `sha256:${sha256(parts.join("\n"))}`;
}

export function readStoredHash(kitRoot) {
  const p = path.join(kitRoot, HASH_FILE);
  if (!pathExists(p)) return null;
  return fs.readFileSync(p, "utf8").split(/\r?\n/)[0].trim();
}

// --- DTCG ------------------------------------------------------------------------

function toDtcgDocument(label, entries) {
  const doc = { $description: `${label}. ${GENERATED}` };
  for (const { group, name, token } of entries) {
    if (token.type === "string") continue;
    if (!doc[group]) doc[group] = {};
    const out = { $type: token.type, $value: toDtcgValue(token) };
    if (token.description) out.$description = token.description;
    if (token.usage) out.$extensions = { "tech.goodheart.bkr": { usage: token.usage } };
    doc[group][name] = out;
  }
  return doc;
}

// --- CSS -------------------------------------------------------------------------

function cssBlock(selector, manifest, entries, indent = "  ") {
  const lines = [`${selector} {`];
  for (const { group, name, token } of entries) {
    const value = toCssValue(token);
    if (value === null) continue;
    lines.push(`${indent}${cssVarName(manifest, group, name)}: ${value};`);
  }
  lines.push("}");
  return lines;
}

function toCss(manifest, tokens) {
  const lines = [`/* ${GENERATED} */`, `/* Brand: ${manifest.brand.id} */`, ""];
  lines.push(...cssBlock(":root", manifest, tokens.base));
  for (const theme of Object.keys(tokens.themes).sort()) {
    const entries = tokens.themes[theme];
    lines.push("");
    if (theme === "dark") {
      lines.push("/* Dark theme: follows the system setting unless the page sets data-theme=\"light\". */");
      lines.push("@media (prefers-color-scheme: dark) {");
      lines.push(...cssBlock(':root:not([data-theme="light"])', manifest, entries).map((l) => `  ${l}`));
      lines.push("}");
      lines.push("");
    }
    lines.push(...cssBlock(`:root[data-theme="${theme}"]`, manifest, entries));
  }
  lines.push("");
  return lines.join("\n");
}

// --- Tailwind ----------------------------------------------------------------------

// Where each token lands in a Tailwind theme. Dimension tokens are routed by group name.
const DIMENSION_GROUPS = {
  fontSize: { v3: "fontSize", v4: "text" },
  radius: { v3: "borderRadius", v4: "radius" },
  spacing: { v3: "spacing", v4: "spacing" },
  space: { v3: "spacing", v4: "spacing" },
};

function tailwindSlot(group, token) {
  switch (token.type) {
    case "color":
      return { v3: "colors", v4: "color", key: `${kebab(group)}-` };
    case "fontFamily":
      return { v3: "fontFamily", v4: "font", key: "" };
    case "fontWeight":
      return { v3: "fontWeight", v4: "font-weight", key: "" };
    case "number":
      return group === "lineHeight" ? { v3: "lineHeight", v4: "leading", key: "" } : null;
    case "dimension": {
      const slot = DIMENSION_GROUPS[group] || { v3: "spacing", v4: "spacing" };
      const key = DIMENSION_GROUPS[group] ? "" : `${kebab(group)}-`;
      return { ...slot, key };
    }
    default:
      return null;
  }
}

// Tailwind v3: tailwind.config.js -> theme: { extend: require(".../theme.cjs") }
function toTailwindV3(manifest, tokens) {
  const theme = {};
  for (const { group, name, token } of tokens.base) {
    const slot = tailwindSlot(group, token);
    if (!slot) continue;
    if (!theme[slot.v3]) theme[slot.v3] = {};
    let value = token.value;
    if (token.type === "fontFamily") value = Array.isArray(value) ? value : [value];
    if (token.type === "fontWeight") value = String(value);
    if (token.type === "number") value = String(value);
    if (token.type === "color") {
      // Nest colors by group: bg-palette-primary
      const g = kebab(group);
      if (!theme.colors[g]) theme.colors[g] = {};
      theme.colors[g][kebab(name)] = value;
      continue;
    }
    theme[slot.v3][`${slot.key}${kebab(name)}`] = value;
  }
  return `/** ${GENERATED} */
/** Brand: ${manifest.brand.id}. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = ${JSON.stringify(theme, null, 2)};
`;
}

// Tailwind v4: @import "./variables.css"; @import "./theme.css";
// Values point at the brand CSS variables, so the dark theme switches automatically.
function toTailwindV4(manifest, tokens) {
  const lines = [
    `/* ${GENERATED} */`,
    `/* Brand: ${manifest.brand.id}. Tailwind v4: import css/variables.css first, then this file. */`,
    "@theme inline {",
  ];
  for (const { group, name, token } of tokens.base) {
    const slot = tailwindSlot(group, token);
    if (!slot) continue;
    lines.push(`  --${slot.v4}-${slot.key}${kebab(name)}: var(${cssVarName(manifest, group, name)});`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

// --- Main ----------------------------------------------------------------------------

export function exportKit(kitRoot, targets) {
  const manifest = readManifest(kitRoot);
  const tokens = loadTokens(kitRoot);
  const want = (t) => targets.includes("all") || targets.includes(t);
  const exportsDir = path.join(kitRoot, "tokens", "exports");
  const results = [];

  const bad = tokens.files.filter((f) => !f.doc);
  if (bad.length) {
    throw new Error(`Cannot export: invalid JSON in ${bad.map((f) => f.rel).join(", ")}`);
  }

  // Remove output from the 0.1 exporter that this version no longer writes.
  for (const stale of ["css/dark-theme.css"]) {
    const p = path.join(exportsDir, stale);
    if (pathExists(p)) fs.rmSync(p);
  }

  if (want("dtcg")) {
    for (const f of tokens.files) {
      const isTheme = f.rel.startsWith("tokens/themes/");
      const base = path.basename(f.rel, ".bkr.json");
      const out = path.join(exportsDir, "dtcg", isTheme ? "themes" : "", `${base}.tokens.json`);
      const entries = tokens.base.filter((t) => t.rel === f.rel);
      const themeEntries = isTheme ? tokens.themes[base] : entries;
      writeJson(out, toDtcgDocument(`DTCG export for ${manifest.brand.id} (${f.rel})`, themeEntries));
      results.push(out);
    }
  }

  if (want("css")) {
    const out = path.join(exportsDir, "css", "variables.css");
    writeText(out, toCss(manifest, tokens));
    results.push(out);
  }

  if (want("tailwind")) {
    const v3 = path.join(exportsDir, "tailwind", "theme.cjs");
    writeText(v3, toTailwindV3(manifest, tokens));
    const v4 = path.join(exportsDir, "tailwind", "theme.css");
    writeText(v4, toTailwindV4(manifest, tokens));
    results.push(v3, v4);
  }

  if (want("html")) {
    const out = path.join(exportsDir, "html", "brand-at-a-glance.html");
    writeText(out, buildBrandAtAGlance(kitRoot, manifest, tokens));
    results.push(out);
  }

  if (want("agent")) {
    const out = path.join(exportsDir, "agent", "ui-brief.md");
    writeText(out, buildUiBrief(kitRoot, manifest, tokens));
    results.push(out);
  }

  // Only a full export refreshes the hash, so a partial export never hides stale files.
  let hashWritten = false;
  if (targets.includes("all")) {
    writeText(
      path.join(kitRoot, HASH_FILE),
      `${computeSourceHash(kitRoot)}\n# ${GENERATED} Used by bkr validate to detect stale exports.\n`
    );
    hashWritten = true;
  }

  return { results, brandId: manifest.brand.id, hashWritten, prefix: cssPrefix(manifest) };
}

// --- Legacy import ---------------------------------------------------------------------

// Converts a GHT-style tokens/colors.json ({ colors: { name: { hex, role } }, doNotUse })
// into tokens/colors.bkr.json for the kit's own brand id.
export function importLegacyGhtColors(kitRoot, sourceJsonPath) {
  const manifest = readManifest(kitRoot);
  const legacy = readJson(sourceJsonPath);
  const colors = legacy.colors || {};
  const tokens = { palette: {} };
  for (const [name, entry] of Object.entries(colors)) {
    const hex = typeof entry === "string" ? entry : entry.hex;
    tokens.palette[name] = {
      value: hex,
      type: "color",
      description: (typeof entry === "object" && (entry.role || entry.description)) || "",
    };
  }
  const doc = {
    $schema: TOKEN_SCHEMA_URL,
    meta: { brandId: manifest.brand.id, layer: "color" },
    tokens,
  };
  if (legacy.doNotUse?.length) {
    doc.guidance = { doNotUse: legacy.doNotUse };
  }
  const out = path.join(kitRoot, "tokens", "colors.bkr.json");
  writeJson(out, doc);
  return out;
}
