import fs from "node:fs";
import path from "node:path";
import {
  ensureDir,
  hashStableString,
  listBkrTokenFiles,
  pathExists,
  readJson,
  readManifest,
  writeJson,
  writeText,
} from "./fs-kit.js";

function flattenColorTokens(doc) {
  const out = [];
  for (const [group, names] of Object.entries(doc.tokens || {})) {
    for (const [name, token] of Object.entries(names)) {
      if (token.type !== "color") continue;
      out.push({
        group,
        name,
        token,
        path: `${group}.${name}`,
      });
    }
  }
  return out;
}

function toDtcgDocument(brandId, colors) {
  const dtcg = {};
  for (const { group, name, token } of colors) {
    if (!dtcg[group]) dtcg[group] = {};
    dtcg[group][name] = {
      $type: "color",
      $value: token.value,
      $description: token.description || undefined,
    };
  }
  return {
    $description: `DTCG export for ${brandId}`,
    ...dtcg,
  };
}

function toCssVariables(brandId, colors, prefix) {
  const lines = [
    "/* Generated by bkr export — do not edit */",
    `/* Brand: ${brandId} */`,
    ":root {",
  ];
  for (const { group, name, token } of colors) {
    const varName = `--${prefix}-${group}-${name}`.replace(/_/g, "-");
    lines.push(`  ${varName}: ${token.value};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function toTailwindTheme(brandId, colors) {
  const theme = { colors: {} };
  for (const { group, name, token } of colors) {
    if (!theme.colors[group]) theme.colors[group] = {};
    theme.colors[group][name] = token.value;
  }
  const body = `/** Generated by bkr export — do not edit */
/** Brand: ${brandId} */
module.exports = ${JSON.stringify(theme, null, 2)};
`;
  return body;
}

export function exportKit(kitRoot, targets) {
  const manifest = readManifest(kitRoot);
  const brandId = manifest.brand.id;
  const prefix = brandId.replace(/-/g, "");

  const colorDocs = listBkrTokenFiles(kitRoot)
    .filter((f) => f.includes("colors.bkr.json"))
    .map((f) => readJson(f));

  let allColors = [];
  for (const doc of colorDocs) {
    allColors = allColors.concat(flattenColorTokens(doc));
  }

  const themePath = path.join(kitRoot, "tokens", "themes", "dark.bkr.json");
  let darkCss = "";
  if (pathExists(themePath)) {
    const darkDoc = readJson(themePath);
    const darkColors = flattenColorTokens(darkDoc);
    darkCss = toCssVariables(`${brandId}-dark`, darkColors, `${prefix}-dark`);
  }

  const results = [];

  if (targets.includes("dtcg") || targets.includes("all")) {
    const out = path.join(kitRoot, "tokens", "exports", "dtcg", "colors.tokens.json");
    writeJson(out, toDtcgDocument(brandId, allColors));
    results.push(out);
  }

  if (targets.includes("css") || targets.includes("all")) {
    const out = path.join(kitRoot, "tokens", "exports", "css", "variables.css");
    writeText(out, toCssVariables(brandId, allColors, prefix));
    results.push(out);
    if (darkCss) {
      const darkOut = path.join(kitRoot, "tokens", "exports", "css", "dark-theme.css");
      writeText(darkOut, darkCss);
      results.push(darkOut);
    }
  }

  if (targets.includes("tailwind") || targets.includes("all")) {
    const out = path.join(kitRoot, "tokens", "exports", "tailwind", "theme.cjs");
    writeText(out, toTailwindTheme(brandId, allColors));
    results.push(out);
  }

  const hashInput = allColors
    .map((c) => `${c.path}=${c.token.value}`)
    .sort()
    .join("|");
  const hashPath = path.join(kitRoot, "tokens", "exports", ".bkr-export-hash");
  writeText(
    hashPath,
    `${hashStableString(hashInput)}\n# sources: ${colorDocs.length} color file(s)\n`
  );

  return { results, brandId };
}

export function importLegacyGhtColors(kitRoot, sourceJsonPath) {
  const legacy = readJson(sourceJsonPath);
  const colors = legacy.colors || {};
  const tokens = { palette: {} };
  for (const [name, entry] of Object.entries(colors)) {
    tokens.palette[name] = {
      value: entry.hex,
      type: "color",
      description: entry.role || entry.description || "",
    };
  }
  const doc = {
    $schema: "https://goodheart.tech/schemas/bkr-token/v1",
    meta: {
      brandId: legacy.name ? legacy.name.toLowerCase().replace(/\s+/g, "-") : "brand",
      layer: "color",
    },
    tokens,
  };
  if (legacy.doNotUse?.length) {
    doc.guidance = { doNotUse: legacy.doNotUse };
  }
  const out = path.join(kitRoot, "tokens", "colors.bkr.json");
  writeJson(out, doc);
  return out;
}
