// Human-readable visuals that render on GitHub (SVG images and markdown blocks).
// GitHub shows SVG images inside markdown, but shows .html files as source code,
// so these are what people actually see when they browse a kit.
//
//   tokens/exports/svg/palette.svg          swatch sheet for README files
//   tokens/exports/svg/palette-<theme>.svg  same, for each theme
//   tokens/exports/svg/contrast.svg         every contrast pair as real text on its background
//   tokens/exports/svg/chips/<token>.svg    small color chip for markdown tables
//   tokens/exports/svg/pairs/<pair>.svg     small "Aa" sample for one contrast pair
//
// Markdown blocks (filled in by `bkr export`, in any .md file):
//   <!-- bkr:palette --> ... <!-- /bkr:palette -->
//   <!-- bkr:contrast --> ... <!-- /bkr:contrast -->
//   <!-- bkr:logos --> ... <!-- /bkr:logos -->
import fs from "node:fs";
import path from "node:path";
import { listFiles } from "./fs-kit.js";
import { cssVarName, evaluateContrast, kebab, parseHex, toPosix } from "./tokens.js";

export const SVG_DIR = "tokens/exports/svg";
const FONT = "system-ui, -apple-system, 'Segoe UI', Roboto, Arial, sans-serif";

const xml = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const ratioText = (r) => `${(Math.floor(r * 100) / 100).toFixed(2)}:1`;

// Near-black or white, whichever reads better on the given color.
function labelOn(hex) {
  const { r, g, b } = parseHex(hex);
  return r * 0.299 + g * 0.587 + b * 0.114 > 150 ? "#111111" : "#FFFFFF";
}

const chipName = (p) => `${kebab(p.split(".")[0])}-${kebab(p.split(".")[1])}.svg`;
const pairName = (row) =>
  `${kebab(row.foreground.replace(".", "-"))}-on-${kebab(row.background.replace(".", "-"))}${row.theme === "base" ? "" : `-${row.theme}`}.svg`;

// --- SVG builders ---------------------------------------------------------------------

function paletteSvg(title, entries, dark) {
  const chipW = 168;
  const chipH = 104;
  const gap = 16;
  const cols = Math.max(1, Math.min(6, entries.length));
  const page = dark ? "#18181B" : "#FFFFFF";
  const ink = dark ? "#F4F4F5" : "#18181B";
  const muted = dark ? "#A1A1AA" : "#52525B";

  // Group colors under their group name (palette, ui, ...).
  const groups = [];
  for (const e of entries) {
    let g = groups.find((x) => x.name === e.group);
    if (!g) groups.push((g = { name: e.group, items: [] }));
    g.items.push(e);
  }

  const width = gap + cols * (chipW + gap);
  let y = 48;
  const parts = [];
  for (const g of groups) {
    if (groups.length > 1) {
      parts.push(`<text x="${gap}" y="${y + 14}" font-size="15" font-weight="700" fill="${muted}">${xml(g.name)}</text>`);
      y += 28;
    }
    g.items.forEach((e, i) => {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = gap + col * (chipW + gap);
      const top = y + row * (chipH + 52 + gap);
      const hex = e.token.value.slice(0, 7);
      parts.push(
        `<rect x="${x}" y="${top}" width="${chipW}" height="${chipH}" rx="10" fill="${xml(hex)}" stroke="${dark ? "#3F3F46" : "#D4D4D8"}"/>`,
        `<text x="${x + 12}" y="${top + chipH - 14}" font-size="14" font-weight="700" fill="${labelOn(hex)}">${xml(hex.toUpperCase())}</text>`,
        `<text x="${x}" y="${top + chipH + 22}" font-size="15" font-weight="700" fill="${ink}">${xml(e.name)}</text>`,
        `<text x="${x}" y="${top + chipH + 42}" font-size="12" fill="${muted}">${xml(e.path)}</text>`
      );
    });
    y += Math.ceil(g.items.length / cols) * (chipH + 52 + gap) + 8;
  }
  const height = y + 8;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(title)}">
<!-- Generated by bkr export. Do not edit by hand. -->
<rect width="${width}" height="${height}" fill="${page}"/>
<g font-family="${FONT}">
<text x="${gap}" y="30" font-size="20" font-weight="700" fill="${ink}">${xml(title)}</text>
${parts.join("\n")}
</g>
</svg>
`;
}

function contrastSvg(title, rows) {
  const width = 960;
  const rowH = 60;
  const ok = rows.filter((r) => !r.error);
  const height = 56 + ok.length * rowH + 16;
  const lines = ok.map((r, i) => {
    const top = 52 + i * rowH;
    const passColor = r.pass ? "#116329" : "#A40E26";
    return [
      `<rect x="16" y="${top}" width="420" height="48" rx="8" fill="${xml(r.bgValue)}" stroke="#D4D4D8"/>`,
      `<text x="32" y="${top + 31}" font-size="18" font-weight="700" fill="${xml(r.fgValue)}">Aa  Sample text in this pair</text>`,
      `<text x="452" y="${top + 21}" font-size="14" font-weight="700" fill="#18181B">${xml(r.foreground)} on ${xml(r.background)}${r.theme === "base" ? "" : ` (${xml(r.theme)})`}</text>`,
      `<text x="452" y="${top + 40}" font-size="12" fill="#52525B">${xml(r.use || "")}</text>`,
      `<text x="800" y="${top + 30}" font-size="15" font-weight="700" fill="#18181B">${ratioText(r.ratio)}</text>`,
      `<text x="880" y="${top + 30}" font-size="15" font-weight="700" fill="${passColor}">${r.pass ? "Pass" : "Fail"}</text>`,
    ].join("\n");
  });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${xml(title)}">
<!-- Generated by bkr export. Do not edit by hand. -->
<rect width="${width}" height="${height}" fill="#FFFFFF"/>
<g font-family="${FONT}">
<text x="16" y="32" font-size="20" font-weight="700" fill="#18181B">${xml(title)}</text>
${lines.join("\n")}
</g>
</svg>
`;
}

function chipSvg(hex) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20"><rect x="0.5" y="0.5" width="19" height="19" rx="4" fill="${xml(hex.slice(0, 7))}" stroke="#00000040"/></svg>
`;
}

function pairSvg(fg, bg) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="56" height="28" viewBox="0 0 56 28"><rect x="0.5" y="0.5" width="55" height="27" rx="5" fill="${xml(bg.slice(0, 7))}" stroke="#00000040"/><text x="28" y="19" text-anchor="middle" font-family="${FONT}" font-size="15" font-weight="700" fill="${xml(fg.slice(0, 7))}">Aa</text></svg>
`;
}

// Writes every SVG and returns the list of written paths.
export function writeSvgExports(kitRoot, manifest, tokens, writeText) {
  const dir = path.join(kitRoot, SVG_DIR);
  if (fs.existsSync(dir)) fs.rmSync(dir, { recursive: true, force: true });
  const out = [];
  const write = (rel, text) => {
    const p = path.join(dir, rel);
    writeText(p, text);
    out.push(p);
  };

  const colors = tokens.base.filter((t) => t.token.type === "color");
  if (colors.length === 0) return out;
  write("palette.svg", paletteSvg(`${manifest.brand.displayName} colors`, colors, false));
  for (const theme of Object.keys(tokens.themes).sort()) {
    const themed = tokens.themes[theme].filter((t) => t.token.type === "color");
    if (themed.length) {
      write(`palette-${theme}.svg`, paletteSvg(`${manifest.brand.displayName} colors (${theme} theme)`, themed, theme === "dark"));
    }
  }
  for (const t of colors) write(`chips/${chipName(t.path)}`, chipSvg(t.token.value));
  for (const [theme, entries] of Object.entries(tokens.themes)) {
    for (const t of entries) {
      if (t.token.type === "color") write(`chips/${chipName(t.path).replace(".svg", "")}-${theme}.svg`, chipSvg(t.token.value));
    }
  }
  const rows = evaluateContrast(manifest, tokens).filter((r) => !r.error);
  if (rows.length) {
    write("contrast.svg", contrastSvg(`${manifest.brand.displayName} text and background pairs`, rows));
    for (const r of rows) write(`pairs/${pairName(r)}`, pairSvg(r.fgValue, r.bgValue));
  }
  return out;
}

// --- Markdown blocks ---------------------------------------------------------------------

const BLOCK = /<!--\s*bkr:(palette|contrast|logos)\s*-->[\s\S]*?<!--\s*\/bkr:\1\s*-->|<!--\s*bkr:(palette|contrast|logos)\s*-->/g;
const cell = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ");

function renderBlock(kind, rel, kitRoot, manifest, tokens) {
  const svg = `${rel}${SVG_DIR}`;
  const themes = Object.keys(tokens.themes).sort();
  if (kind === "palette") {
    const colors = tokens.base.filter((t) => t.token.type === "color");
    const head = ["Color", "Token", "Hex", ...themes.map((th) => th[0].toUpperCase() + th.slice(1)), "CSS variable", "Use"];
    const rows = [`| ${head.join(" | ")} |`, `|${head.map(() => "---").join("|")}|`];
    for (const t of colors) {
      const themeCells = themes.map((th) => {
        const o = tokens.themes[th].find((x) => x.path === t.path);
        return o ? `![${o.token.value}](${svg}/chips/${chipName(t.path).replace(".svg", "")}-${th}.svg) \`${o.token.value}\`` : "same";
      });
      const use = t.token.description || "";
      rows.push(
        `| ![${t.token.value}](${svg}/chips/${chipName(t.path)}) | \`${t.path}\` | \`${t.token.value}\` | ${themeCells.join(" | ")}${themeCells.length ? " | " : ""}\`${cssVarName(manifest, t.group, t.name)}\` | ${cell(use)} |`
      );
    }
    return `![${manifest.brand.displayName} colors](${svg}/palette.svg)\n\n${rows.join("\n")}`;
  }
  if (kind === "contrast") {
    const rows = ["| Sample | Text | Background | Theme | Use | Contrast | Needs | Result |", "|---|---|---|---|---|---|---|---|"];
    for (const r of evaluateContrast(manifest, tokens).filter((x) => !x.error)) {
      rows.push(
        `| ![sample](${svg}/pairs/${pairName(r)}) | \`${r.foreground}\` | \`${r.background}\` | ${r.theme} | ${cell(r.use)} | ${ratioText(r.ratio)} | ${r.min}:1 | ${r.pass ? "Pass" : "**Fail**"} |`
      );
    }
    return rows.length > 2 ? rows.join("\n") : "_No contrast pairs listed in brandkit.yaml._";
  }
  // logos
  const logos = listFiles(path.join(kitRoot, "assets", "logo"))
    .map((f) => toPosix(path.relative(kitRoot, f)))
    .filter((f) => /\.(svg|png|jpe?g|webp)$/i.test(f));
  if (!logos.length) return "_No logo files in assets/logo/._";
  return logos.map((f) => `<img src="${rel}${f}" alt="${path.posix.basename(f)}" height="72"> \`${f}\``).join("<br>\n");
}

// Markdown files that may hold blocks (kit docs, not generated output).
function docFiles(kitRoot, manifest) {
  const digest = toPosix(path.normalize(manifest.consumption?.agentDigest || ""));
  return listFiles(kitRoot)
    .map((f) => [f, toPosix(path.relative(kitRoot, f))])
    .filter(([, rel]) => rel.endsWith(".md") && !rel.startsWith("tokens/exports/") && rel !== digest && rel !== "AGENTS.md");
}

function fill(text, file, kitRoot, manifest, tokens) {
  const depth = path.posix.dirname(toPosix(path.relative(kitRoot, file)));
  const rel = depth === "." ? "" : `${depth.split("/").map(() => "..").join("/")}/`;
  return text.replace(BLOCK, (_m, a, b) => {
    const kind = a || b;
    return `<!-- bkr:${kind} -->\n<!-- Generated by bkr export from tokens/ and brandkit.yaml. Edit those, not this block. -->\n${renderBlock(kind, rel, kitRoot, manifest, tokens)}\n<!-- /bkr:${kind} -->`;
  });
}

// Fills every block. Returns the files that changed.
export function updateMarkdownBlocks(kitRoot, manifest, tokens) {
  const changed = [];
  for (const [file] of docFiles(kitRoot, manifest)) {
    const raw = fs.readFileSync(file, "utf8");
    if (!/<!--\s*bkr:(palette|contrast|logos)\s*-->/.test(raw)) continue;
    const eol = raw.includes("\r\n") ? "\r\n" : "\n";
    const next = fill(raw.replace(/\r\n/g, "\n"), file, kitRoot, manifest, tokens).replace(/\n/g, eol);
    if (next !== raw) {
      fs.writeFileSync(file, next, "utf8");
      changed.push(file);
    }
  }
  return changed;
}

// For validate: files whose blocks are out of date, and whether the README shows colors.
export function checkMarkdownBlocks(kitRoot, manifest, tokens) {
  const stale = [];
  let readmeVisual = false;
  for (const [file, rel] of docFiles(kitRoot, manifest)) {
    const raw = fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n");
    if (rel === "README.md" && (raw.includes(`${SVG_DIR}/palette.svg`) || /<!--\s*bkr:palette\s*-->/.test(raw))) {
      readmeVisual = true;
    }
    if (!/<!--\s*bkr:(palette|contrast|logos)\s*-->/.test(raw)) continue;
    if (fill(raw, file, kitRoot, manifest, tokens) !== raw) stale.push(rel);
  }
  return { stale, readmeVisual };
}
