/** Generated by bkr export — do not edit */
/** Brand: acme-labs */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2563EB",
      "ink": "#0F172A",
      "body": "#334155",
      "surface": "#FFFFFF",
      "accent": "#38BDF8"
    }
  }
};
