/** Generated by bkr export. Do not edit by hand. */
/** Brand: acme-labs. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2563EB",
      "on-primary": "#FFFFFF",
      "link": "#1D4ED8",
      "ink": "#0F172A",
      "body": "#334155",
      "surface": "#FFFFFF",
      "subtle": "#EFF6FF",
      "accent": "#38BDF8"
    }
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "40px"
  },
  "borderRadius": {
    "sm": "4px",
    "md": "8px",
    "lg": "16px"
  },
  "fontFamily": {
    "heading": [
      "Inter",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "sans-serif"
    ],
    "body": [
      "Inter",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "sans-serif"
    ],
    "mono": [
      "JetBrains Mono",
      "ui-monospace",
      "Consolas",
      "monospace"
    ]
  },
  "fontWeight": {
    "regular": "400",
    "semibold": "600",
    "bold": "700"
  },
  "fontSize": {
    "small": "0.875rem",
    "base": "1rem",
    "large": "1.25rem",
    "heading": "2rem",
    "display": "3rem"
  },
  "lineHeight": {
    "tight": "1.2",
    "normal": "1.6"
  }
};
