/** Generated by obks export. Do not edit by hand. */
/** Brand: juniper-lane-studio. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2F5D50",
      "on-primary": "#FFFFFF",
      "link": "#2E6B58",
      "charcoal": "#2B2B2B",
      "paper": "#FAF6F0",
      "white": "#FFFFFF",
      "blush": "#E8B4A8",
      "wash": "#E6EFEA"
    }
  },
  "fontFamily": {
    "heading": [
      "Cormorant Garamond",
      "Georgia",
      "Times New Roman",
      "serif"
    ],
    "body": [
      "Karla",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "sans-serif"
    ]
  },
  "fontWeight": {
    "regular": "400",
    "bold": "700"
  },
  "fontSize": {
    "small": "0.875rem",
    "base": "1.0625rem",
    "large": "1.375rem",
    "heading": "2.25rem"
  },
  "lineHeight": {
    "tight": "1.15",
    "normal": "1.6"
  }
};
