/** Generated by bkr export. Do not edit by hand. */
/** Brand: minimal-brand. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#B4232A",
      "text": "#1C1917",
      "background": "#FFFFFF"
    }
  }
};
