/** Generated by obks export. Do not edit by hand. */
/** Brand: brightwater-county. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#1B4F8A",
      "on-primary": "#FFFFFF",
      "link": "#1A5DAB",
      "ink": "#0B1F33",
      "body": "#2B3A4A",
      "surface": "#FFFFFF",
      "subtle": "#EAF2FA",
      "success": "#2E7D4F",
      "alert": "#F2B632",
      "on-alert": "#0B1F33"
    }
  },
  "fontFamily": {
    "heading": [
      "Public Sans",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "Arial",
      "sans-serif"
    ],
    "body": [
      "Public Sans",
      "system-ui",
      "-apple-system",
      "Segoe UI",
      "Arial",
      "sans-serif"
    ]
  },
  "fontWeight": {
    "regular": "400",
    "semibold": "600",
    "bold": "700"
  },
  "fontSize": {
    "small": "1rem",
    "base": "1.125rem",
    "large": "1.375rem",
    "heading": "2.25rem",
    "display": "3rem"
  },
  "lineHeight": {
    "tight": "1.25",
    "normal": "1.6"
  }
};
