/** Generated by bkr export — do not edit */
/** Brand: acme-docs */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2563EB",
      "ink": "#0F172A",
      "surface": "#FFFFFF",
      "productAccent": "#7C3AED"
    }
  }
};
