/** Generated by bkr export. Do not edit by hand. */
/** Brand: acme-docs. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2563EB",
      "on-primary": "#FFFFFF",
      "link": "#1D4ED8",
      "ink": "#0F172A",
      "surface": "#FFFFFF",
      "product-accent": "#7C3AED"
    }
  }
};
